[package]
name = "my_flipper_guard"
version = "3.0.0-beta"
authors = ["Brushfam <green@727.ventures>"]
edition = "2021"

[dependencies]
ink = { git = "https://github.com/paritytech/ink", commit = "4655a8b4413cb50cbc38d1b7c173ad426ab06cde", default-features = false}

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

# These dependencies
flipper = { path = "../..", default-features = false }
openbrush = { path = "../../../..", default-features = false }

[lib]
name = "my_flipper_guard"
path = "lib.rs"

crate-type = [
    "cdylib",
]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    # These dependencies
    "flipper/std",
    "openbrush/std",
]

ink-as-dependency = []

[profile.dev]
codegen-units = 16